---
engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      complexity:
        enabled: false
    config:
      sanitize_batch: false
      extensions:
       - .js
       - .html

  duplication:
    enabled: true
    config:
      languages:
        - javascript

  fixme:
    enabled: true
    exclude_paths:
      - "analysis.json"

ratings:
  paths:
  - "**.js"
  - "**.html"
